# Site settings
title_left    : "LZX's"
title_right   : " spaceship" # default: ""
description   : "about cs learning."
keywords      : "cs code"
url           : https://cookieli.github.io # site url
baseurl       : "/blog" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : coder.lzx.dev@gmail.com
twitter_username  : ""
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "lzx"
postshare_enabled : true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "John Doe"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
